add eth2 withdrawal address derive feature
consenlabs/token-core pull request #90
Opened 2021-02-09 05:02 UTC by xiaoguang1010

2021-02-09 07:03 UTC, tyrone98 requested changes
去除所有的 WARNING

2021-02-09 07:05 UTC, XuNeal commented on tcx/src/lib.rs
> +            // assert_eq!(
这个为啥被注释掉了？

2021-02-09 07:05 UTC, XuNeal commented on tcx/src/lib.rs
> +                "a9bedcb23b8ea49d9171a75eacaa90733df0c5e92be5298c2e2e3d001afc0a9ba99e146796cf1d6e93b1778c3e89edac",
现在这里了存放的的是公钥吧。已经确定 eth2 的地址一定会是公钥是吧。还是说会存在其他形式？如果不确定是否放到 account 中的 pulic_key 字段更合适？

2021-02-18 02:47 UTC, xiaoguang1010 commented on tcx/src/lib.rs
> +            // assert_eq!(
BLS派生的代码做了些修改后，对FILECOIN产生了影响，但是孙总说FILECOIN并没有用到，所以可以先注释掉。
![image](https://user-images.githubusercontent.com/40228114/108297702-a3cd1a80-71d6-11eb-8238-ac18469a12e3.png)

2021-02-18 02:48 UTC, xiaoguang1010 commented on tcx/src/lib.rs
> +                "a9bedcb23b8ea49d9171a75eacaa90733df0c5e92be5298c2e2e3d001afc0a9ba99e146796cf1d6e93b1778c3e89edac",
已经确认，目前ETH2地址没有相关的规范描述，直接用公钥作为地址。

2021-04-23 03:27 UTC, tyrone98 requested changes

2021-04-23 03:27 UTC, tyrone98 commented on tcx-primitive/src/bls.rs
> +        match data.len() {
用 data.clone().resize(32, 0u8) 代码会更简单点

2021-04-23 06:26 UTC, pikang commented on tcx/src/lib.rs
> +                "a9bedcb23b8ea49d9171a75eacaa90733df0c5e92be5298c2e2e3d001afc0a9ba99e146796cf1d6e93b1778c3e89edac",
看到评论想确认一下，当前 Eth2 生成的是 pubkey，address 后续应该会有规范出来的，这里目前的实现是用了 accout 来存放还是用 pulic_key？

2021-04-23 08:06 UTC, xiaoguang1010 commented on tcx/src/lib.rs
> +                "a9bedcb23b8ea49d9171a75eacaa90733df0c5e92be5298c2e2e3d001afc0a9ba99e146796cf1d6e93b1778c3e89edac",
现在用accoout来存放的，tcx这个pubkey是通过getAddress接口来获取的，以后这个地址不是公钥，修改getAddress接口即可。

2021-04-23 08:32 UTC, tyrone98 approved these changes

2022-09-19 09:13 UTC, closed without merging