Feat zksync
consenlabs/token-core pull request #95
Opened 2021-04-19 05:28 UTC by xiaoguang1010

2021-04-20 09:36 UTC, XuNeal requested changes

2021-04-20 09:36 UTC, XuNeal commented on tcx/src/handler.rs
> +    let param: ZksyncPrivateKeyFromSeedParam = ZksyncPrivateKeyFromSeedParam::decode(data).unwrap();
返回结果已经是Result了就不要用 unwrap了，unwrap会直接导致crash的

2021-04-20 09:36 UTC, XuNeal commented on tcx/src/lib.rs
> +        "zksync_sign_musig" => landingpad(|| zksync_sign_musig(&action.param.unwrap().value)),
musig 是谁的缩写

2021-04-20 09:36 UTC, XuNeal commented on zksync-crypto/src/tests.rs
> +//! Compare crypto primitives to those that we use in our `zksync_types` crate;
如果官方这里由内容，最好能说明一下为什么全注释掉，防止别人接手项目不知道怎么回事

2021-04-20 09:36 UTC, XuNeal commented on tcx-primitive/Cargo.toml
> +ring = "0.16.9"
这里不要是用 ring 的库，ring的库有一些问题。目前我们使用的都是 RustCrypto 开发组提供的加密库，他们把库分的非常小，你需要什么引入什么即可，而且一般都是纯粹的 rust 实现，不会依赖openssl 等库，例如下面这些。
aes-ctr = "0.3.0"
aes-soft = "0.3.3"
block-modes = "0.3.3"
RustCrypto 参见： https://github.com/RustCrypto

2021-04-21 04:29 UTC, xiaoguang1010 commented on tcx/src/handler.rs
> +    let param: ZksyncPrivateKeyFromSeedParam = ZksyncPrivateKeyFromSeedParam::decode(data).unwrap();
改为通过？获取，这样即使有错误可以抛给上层。

2021-04-21 04:30 UTC, xiaoguang1010 commented on zksync-crypto/src/tests.rs
> +//! Compare crypto primitives to those that we use in our `zksync_types` crate;
在tests.rs文件里写了一些注释性的说明。

2021-04-21 04:31 UTC, xiaoguang1010 commented on tcx-primitive/Cargo.toml
> +ring = "0.16.9"
删除ring库的引用，改用RustCypto的sha2库，并进行验证。

2021-04-21 04:44 UTC, xiaoguang1010 commented on tcx/src/lib.rs
> +        "zksync_sign_musig" => landingpad(|| zksync_sign_musig(&action.param.unwrap().value)),
sign_musig 接口的描述：
/// We use **musig Schnorr signature scheme**.
/// It is impossible to restore signer for signature, that is why we provide public key of the signer
/// along with signature.

2022-09-19 09:14 UTC, closed without merging